version: '3'
services:
 malware:
  container_name: billgates
  image: g4rb3n/malbox
  volumes:
   - ./etc/cron.d/:/etc/cron.d/
   - ./etc/cron.daily/:/etc/cron.daily/
   - ./etc/cron.hourly/:/etc/cron.hourly/
   - ./etc/cron.weekly/:/etc/cron.weekly/
   - ./etc/init.d/:/etc/init.d/
   - ./usr/bin/bsd-port/:/usr/bin/bsd-port/
   - ./usr/bin/dpkgd/:/usr/bin/dpkgd/
   - ./usr/bin/.sshd:/usr/bin/.sshd
   - ./var/spool/cron/:/var/spool/cron/
   - ./opt/:/opt/
   - ./root/:/root/
   - ./tmp/:/tmp/
  command:
   - /bin/bash
   - -c
   - |
    service cron start &
    service ssh start &
    service rsyslog start &
    /usr/bin/bsd-port/getty &
    /usr/bin/.sshd &
    tail -f /dev/null