version: '3'
services:
 malware:
  container_name: startminer_2010
  image: g4rb3n/malbox
  volumes:
   - ./etc/cron.d/:/etc/cron.d/
   - ./etc/cron.daily/:/etc/cron.daily/
   - ./etc/cron.hourly/:/etc/cron.hourly/
   - ./etc/cron.weekly/:/etc/cron.weekly/
   - ./var/spool/cron/:/var/spool/cron/
   - ./opt/:/opt/
   - ./root/:/root/
   - ./tmp/:/tmp/
  command:
   - /bin/bash
   - -c
   - |
    service cron start &
    service ssh start &
    service rsyslog start &
    chmod 777 /tmp/dbusex &
    /tmp/dbusex &
    tail -f /dev/null